// web/src/pages/Schemas.tsx
import { useEffect, useState } from 'react';
import { Table, FileInput, TextInput, Button, Group, Code, Stack, ActionIcon, Tooltip, Modal, Text } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { notifications } from '@mantine/notifications';
import { IconTrash } from '@tabler/icons-react';
import { supabase } from '@/lib/supabase';
import { edgeJson } from '@/lib/edge';
import { TABLES } from '@/lib/tables';
import type { SchemaRow } from '@/lib/types';
import { PageHeader } from '@/components/common/PageHeader';
import { ErrorAlert } from '@/components/common/ErrorAlert';

export default function Schemas() {
  const [rows, setRows] = useState<SchemaRow[]>([]);
  const [file, setFile] = useState<File | null>(null);
  const [schemaRef, setSchemaRef] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastUpload, setLastUpload] = useState<unknown>(null);
  const [deleteTarget, setDeleteTarget] = useState<SchemaRow | null>(null);
  const [deleteOpened, { open: openDelete, close: closeDelete }] = useDisclosure(false);
  const [deleting, setDeleting] = useState(false);

  const load = () => {
    supabase
      .from(TABLES.schemas)
      .select('schema_id, schema_ref, schema_uid, created_at, owner_id, schema_jsonb')
      .order('created_at', { ascending: false })
      .limit(50)
      .then(({ data, error: err }) => {
        if (err) setError(err.message);
        else setRows((data ?? []) as SchemaRow[]);
      });
  };

  useEffect(load, []);

  const handleDeleteSchema = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      const { error: err } = await supabase.rpc('delete_schema', { p_schema_id: deleteTarget.schema_id });
      if (err) throw new Error(err.message);
      notifications.show({ color: 'green', title: 'Deleted', message: `Schema "${deleteTarget.schema_ref}" removed` });
      closeDelete();
      setDeleteTarget(null);
      load();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      closeDelete();
    } finally {
      setDeleting(false);
    }
  };

  const upload = async () => {
    if (!file) { setError('Choose a schema JSON file first.'); return; }
    setBusy(true);
    setError(null);
    setLastUpload(null);
    try {
      const form = new FormData();
      if (schemaRef.trim()) form.set('schema_ref', schemaRef.trim());
      form.set('schema', file);
      const result = await edgeJson('schemas', { method: 'POST', body: form });
      setLastUpload(result);
      load();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      <PageHeader title="Schemas" subtitle="Upload and list annotation schemas." />
      <Stack maw={700} gap="sm">
        <Group grow>
          <TextInput placeholder="schema_ref (optional)" value={schemaRef} onChange={(e) => setSchemaRef(e.currentTarget.value)} />
          <FileInput placeholder="Choose .json file" accept="application/json,.json" value={file} onChange={setFile} />
          <Button onClick={upload} loading={busy}>Upload schema</Button>
        </Group>
      </Stack>
      {error && <ErrorAlert message={error} />}
      {lastUpload && <Code block mt="md">{JSON.stringify(lastUpload, null, 2)}</Code>}
      <Table.ScrollContainer minWidth={500} mt="lg">
        <Table striped highlightOnHover>
          <Table.Thead>
            <Table.Tr>
              <Table.Th>schema_ref</Table.Th>
              <Table.Th>schema_uid</Table.Th>
              <Table.Th>created</Table.Th>
              <Table.Th w={50} />
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {rows.map((r) => (
              <Table.Tr key={r.schema_id}>
                <Table.Td ff="monospace" fz="xs">{r.schema_ref}</Table.Td>
                <Table.Td ff="monospace" fz="xs">{r.schema_uid.slice(0, 16)}...</Table.Td>
                <Table.Td>{new Date(r.created_at).toLocaleString()}</Table.Td>
                <Table.Td>
                  <Tooltip label="Delete schema">
                    <ActionIcon variant="subtle" color="red" size="sm" onClick={() => { setDeleteTarget(r); openDelete(); }}>
                      <IconTrash size={14} />
                    </ActionIcon>
                  </Tooltip>
                </Table.Td>
              </Table.Tr>
            ))}
            {rows.length === 0 && (
              <Table.Tr>
                <Table.Td colSpan={4} ta="center" c="dimmed">No schemas yet.</Table.Td>
              </Table.Tr>
            )}
          </Table.Tbody>
        </Table>
      </Table.ScrollContainer>

      <Modal opened={deleteOpened} onClose={closeDelete} title="Delete schema" centered>
        <Stack gap="md">
          <Text size="sm">
            Delete schema <Text span fw={600} ff="monospace">{deleteTarget?.schema_ref}</Text>? This will fail if any runs reference it.
          </Text>
          <Group justify="flex-end">
            <Button variant="default" onClick={closeDelete}>Cancel</Button>
            <Button color="red" onClick={handleDeleteSchema} loading={deleting}>Delete</Button>
          </Group>
        </Stack>
      </Modal>
    </>
  );
}

// frontend/src/routes/app/schemas/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { supabase } from '$lib/supabase';
  import { edgeJson } from '$lib/edge';

  type SchemaRow = { schema_id: string; schema_ref: string; schema_uid: string; created_at: string };

  let rows: SchemaRow[] = [];
  let file: File | null = null;
  let schema_ref = '';
  let busy = false;
  let error: string | null = null;
  let lastUpload: unknown = null;

  function onFileChange(e: Event) {
    const input = e.currentTarget as HTMLInputElement;
    file = input.files?.[0] ?? null;
  }

  async function load() {
    error = null;
    busy = true;
    try {
      const { data, error: err } = await supabase
        .from('schemas')
        .select('schema_id, schema_ref, schema_uid, created_at')
        .order('created_at', { ascending: false })
        .limit(50);
      if (err) throw err;
      rows = (data ?? []) as SchemaRow[];
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      busy = false;
    }
  }

  async function upload() {
    error = null;
    lastUpload = null;
    if (!file) {
      error = 'Choose a schema JSON file first.';
      return;
    }
    busy = true;
    try {
      const form = new FormData();
      if (schema_ref.trim()) form.set('schema_ref', schema_ref.trim());
      form.set('schema', file);
      lastUpload = await edgeJson('schemas', { method: 'POST', body: form });
      await load();
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      busy = false;
    }
  }

  onMount(load);
</script>

<div class="card">
  <h1 style="margin-top: 0">Schemas</h1>
  <p class="muted">Phase 2 scaffolding: upload and list annotation schemas.</p>

  <div class="row" style="margin-top: 12px">
    <input class="input" placeholder="schema_ref (optional)" bind:value={schema_ref} />
    <input class="input" type="file" accept="application/json,.json" on:change={onFileChange} />
    <button class="btn" disabled={busy} on:click={upload}>{busy ? 'Uploading…' : 'Upload schema'}</button>
    <button class="btn secondary" disabled={busy} on:click={load}>Refresh</button>
  </div>

  {#if error}
    <p style="color: var(--danger)">{error}</p>
  {/if}
  {#if lastUpload}
    <pre>{JSON.stringify(lastUpload, null, 2)}</pre>
  {/if}

  <table style="margin-top: 12px">
    <thead>
      <tr>
        <th>schema_ref</th>
        <th>schema_uid</th>
        <th>created</th>
      </tr>
    </thead>
    <tbody>
      {#each rows as r}
        <tr>
          <td class="muted"><code>{r.schema_ref}</code></td>
          <td class="muted"><code>{r.schema_uid}</code></td>
          <td class="muted">{new Date(r.created_at).toLocaleString()}</td>
        </tr>
      {/each}
      {#if !busy && rows.length === 0}
        <tr>
          <td colspan="3" class="muted">No schemas yet.</td>
        </tr>
      {/if}
    </tbody>
  </table>
</div>
